name: rapid_note
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  just_audio: ^0.9.36
  permission_handler: ^11.1.0
  record: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
